spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recipe
    username: postgres
    password: Postgres1225!
    hikari:
      initialization-fail-timeout: 0
jpa:
  database-platform: org.hibernate.dialect.PostgreSQL82Dialect
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: update